container:
    image: cirrusci/android-sdk:30
    cpu: 6
    memory: 10G
    kvm: true

android_lint_task:
    name: Android Lint
    lint_script: ./gradlew lint
    always:
        android_lint_artifacts:
            path: "build/reports/lint-results.xml"
            type: text/xml
            format: android-lint

android_unit_tests_task:
    name: Unit tests
    unit_test_script: ./gradlew test
    always:
        results_artifacts:
            path: "build/test-results/test*/*.xml"
            type: text/xml
            format: junit
